[build]
  command = "ls -l public"
  functions = "functions"

[dev]
  command = "yarn start"
    functions = "netlify/functions"
[[redirects]]
  from = "/*"
  to = "/public/index.html"
  status = 200
